local o = vim.opt
local g = vim.g

local tabstop = 4
local scroll_off = 10
local cmd_height = 1

o.encoding = "UTF-8"
o.number = true
-- o.ruler = true
o.mouse = "a"
o.showmode = false
o.cmdheight = cmd_height
o.cmdwinheight = cmd_height
o.smarttab = true
o.smartindent = true
o.breakindent = true
o.wrap = true
o.tabstop = tabstop
o.softtabstop = tabstop
o.shiftwidth = tabstop
o.shiftround = true
o.expandtab = true
o.emoji = true
-- o.wildmode = 'longest,list,full'
o.splitright = true
o.splitbelow = true
o.splitkeep = "screen"
o.signcolumn = "yes"
o.foldenable = false
-- o.foldcolumn = "1"
o.foldlevel = 0
o.foldlevelstart = 0
o.foldmethod = "marker"
o.foldexpr = "v:lua.vim.treesitter.foldexpr()"
-- o.updatetime = 0
o.scrolloff = scroll_off
o.sidescrolloff = scroll_off
o.hlsearch = true
o.pumheight = 10
o.termguicolors = true
o.timeoutlen = 300
-- o.backup = false
o.cursorline = true
o.hidden = true
-- o.swapfile = false
o.colorcolumn = "80"
-- o.clipboard = "unnamedplus"
o.inccommand = "split"
o.shada = { "'10", "<0", "s10", "h" }
o.smartcase = true
o.ignorecase = true
o.list = true
o.background = "dark"
o.completeopt = { "menu", "menuone", "noselect" }
o.shortmess = o.shortmess:append({ c = true })
o.formatoptions = o.formatoptions:remove("o")
o.listchars = o.listchars:append({
  trail = "·",
  extends = "»",
  precedes = "«",
  nbsp = "░",
})
o.modeline = true

g.gitblame_enabled = 0
g.have_nerd_font = true
g.loaded_netrw = 1
g.loaded_netrwPlugin = 1
g.showbreak = "↪"
g.showmatch = true
g.netrw_banner = 0
